name: Freetube-armhf

on:
  push:
    branches: [ master ]
    paths-ignore: [README.md]
  pull_request:
    branches: [ master ]
    paths-ignore: [README.md]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: save working directory in variable 'DIR'
        run: echo "DIR=$(pwd)" >> $GITHUB_ENV

      - name: save current date to the 'DATE' variable
        run: echo "DATE=$(date +"%F")" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt -y install git python gcc g++ make libx11-dev libxkbfile-dev fakeroot rpm libsecret-1-dev jq python2.7-dev python3-pip python-setuptools libudev-dev ruby-dev
          sudo gem install fpm -v 1.10.2 --no-document
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
      - name: clone etcher repo and checkout latest release
        run: |
          cd $DIR
          git clone --recursive https://github.com/FreeTubeApp/FreeTube
          cd FreeTube
      - name: Build
        run: |
          cd $DIR/FreeTube
          pip install -r requirements.txt
          make electron-develop
          USE_SYSTEM_FPM=true make electron-build
          echo "DEB=$(basename dist/freetube_*_armv7l.deb)" >> $GITHUB_ENV
      - name: prepare-upload
        run: |
          cd $DIR/
          mkdir freetube-armv7l_$DATE/
          mv FreeTube/dist/$DEB freetube-armv7l_$DATE/
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: freetube-armv7l_${{ env.DATE }}
          path: ${{ env.DIR }}/freetube-armv7l_${{ env.DATE }}/
