name: stuntrally-arm64

on:
  workflow_dispatch:

jobs:
  stuntrally-arm64:
    runs-on: ubuntu-latest
    name: stuntrally-arm64 
    steps:
      - uses: actions/checkout@v2
      - uses: darsvador/run-on-arch-action@v1.0.10
        with:
          architecture: aarch64
          distribution: ubuntu20.04
          run: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt install git zip -y
            apt install build-essential -y
            apt install libboost-wave-dev -y
            apt install libboost-system-dev -y
            apt install libboost-filesystem-dev -y
            apt install libboost-thread-dev -y
            apt install libogre-1.9-dev -y
            apt install libmygui-dev -y
            apt install libsdl2-dev -y
            apt install libogg-dev -y
            apt install libvorbis-dev cmake -y
            apt install libenet-dev -y
            apt install libopenal-dev -y
            apt install libbullet-dev -y
            apt install libbullet-extras-dev -y
            git clone --depth=1 git://github.com/stuntrally/stuntrally.git stuntrally
            git clone --depth=1 git://github.com/stuntrally/stuntrally.git stuntrally
            cd stuntrally/data
            git clone --depth=1 git://github.com/stuntrally/tracks.git tracks
            cd ..
            mkdir build
            cd build
            cmake ..
            make -j4
            make install
            cd ..
            mv build stuntrally
            zip -r stuntrally.zip stuntrally/
            echo "FILE=$(basename stuntrally.zip)" >> $GITHUB_ENV
      - name: gen-date
        run: echo "DATE=$(date +"%F")" >> $GITHUB_ENV
      - name: prepare-upload
        run: |
          cd $DIR/
          mkdir stuntrally-arm64_$DATE/
          mv stuntrally/$FILE stuntrally-arm64_$DATE/
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: stuntrally-arm64_${{ env.DATE }}
          path: ${{ env.DIR }}/stuntrally-arm64_${{ env.DATE }}/
