name: stuntrally-arm64

on:
  push:
    branches: [ master ]
    paths-ignore: [README.md]
  pull_request:
    branches: [ master ]
    paths-ignore: [README.md]

jobs:
  stuntrally-arm64:
    runs-on: ubuntu-latest
    name: stuntrally-arm64 
    steps:
      - uses: actions/checkout@v2
      - uses: darsvador/run-on-arch-action@v1.0.10
        with:
          architecture: aarch64
          distribution: ubuntu20.04
          run: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get update
            sudo apt install git zip -y
            sudo apt install build-essential -y
            sudo apt install libboost-wave-dev -y
            sudo apt install libboost-system-dev -y
            sudo apt install libboost-filesystem-dev -y
            sudo apt install libboost-thread-dev -y
            sudo apt install libogre-1.9-dev -y
            sudo apt install libmygui-dev -y
            sudo apt install libsdl2-dev -y
            sudo apt install libogg-dev -y
            sudo apt install libvorbis-dev -y
            sudo apt install libenet-dev -y
            sudo apt install libopenal-dev -y
            sudo apt install libbullet-dev -y
            sudo apt install libbullet-extras-dev -y
            git clone --depth=1 git://github.com/stuntrally/stuntrally.git stuntrally
            git clone --depth=1 git://github.com/stuntrally/stuntrally.git stuntrally
            cd stuntrally/data
            git clone --depth=1 git://github.com/stuntrally/tracks.git tracks
            cd ..
            mkdir build
            cd build
            cmake ..
            make -j4
            sudo make install
            cd ..
            mv build stuntrally
            zip -r stuntrally.zip stuntrally/
            echo "FILE=$(basename stuntrally.zip)" >> $GITHUB_ENV
      - name: gen-date
        run: echo "DATE=$(date +"%F")" >> $GITHUB_ENV
      - name: prepare-upload
        run: |
          cd $DIR/
          mkdir stuntrally-arm64_$DATE/
          mv stuntrally/$FILE stuntrally-arm64_$DATE/
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: etcher-arm64_${{ env.DATE }}
          path: ${{ env.DIR }}/stuntrally-arm64_${{ env.DATE }}/
